FROM pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel as base

RUN pip install pybind11-global==2.10.1

RUN apt-get update

RUN apt-get install --yes libboost-all-dev

FROM base AS builder

RUN apt-get install --yes --no-install-recommends cmake build-essential

COPY ./. /MAPF/codes/ 

WORKDIR /MAPF/codes/

RUN sh compile-opss25.sh 

FROM base

COPY --from=builder /MAPF/codes/build /MAPF/codes/build

RUN python3 -m pip install numpy

WORKDIR /MAPF/codes/

ENTRYPOINT ["/MAPF/codes/build/lifelong"]

