version: 1.4.0
views:
  main:
  - $: rect
    $if: ${{ $.type != 'stats' }}
    alpha: '${{ ($.expanded || $.type == ''generating'' || $.type == ''generating-new'')
      ? 0.2 : 1 }}'
    direction: ${{ $.direction }}
    fill: '${{ ({ destination: color.red, source: color.green, close: color.pink,
      expand: color.deepPurple, generating: color.amber, ''generating-new'': color.amber,
      ''generating-pruned'': color.blueGrey, ''dominated-by'': color.amber, ''relaxed-by'':
      color.amber, solution: color.blue })[$.type] ?? theme.accent }}'
    height: 1
    t: ${{ $.t }}
    width: 1
    x: ${{ $.x }}
    y: ${{ $.y }}
pivot:
  scale: 1
  x: ${{ $.x + 0.5 }}
  y: ${{ $.y + 0.5 }}
events:
- {depth: 0, direction: 1, f: 9.21954, g: 0, h: 9.21954, id: graph-iicOEUAd0, pId: null, t: 0, type: source, x: 30, y: 5}
- {depth: 0, direction: 4, f: 0.0, g: 0, h: 0.0, id: graph-ljdTTq6dt, pId: null, t: -1, type: destination, x: 28, y: 14}
- {depth: 0, direction: 1, f: 9.21954, g: 0, h: 9.21954, id: graph-iicOEUAd0, pId: null, t: 0, type: expand, x: 30, y: 5}
